set(CORE_FILES
  ${CMAKE_CURRENT_SOURCE_DIR}/Core/Interfaces/Calculator.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Core/DerivedModule.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Core/Exceptions.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Core/ExportControl.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Core/Module.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Core/ModuleManager.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Core/ModuleManager.h
)
